PATH="/usr/local/Cellar/coreutils/8.22/libexec/gnubin:$PATH"
MANPATH="/usr/local/Cellar/coreutils/8.22/libexec/gnuman:$MANPATH"

test -e ~/.dircolors && \
  eval `dircolors -b ~/.dircolors`

alias ls="ls --color=always"
alias grep="grep --color=always"
alias egrep="egrep --color=always"

alias vim="mvim -v"

source ~/.git-completion.sh

set -o vi
