PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

test -e ~/.dircolors && \
  eval `dircolors -b ~/.dircolors`

alias ls="ls --color=always"
alias grep="grep --color=always"
alias egrep="egrep --color=always"

alias vim="nvim"

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

set -o vi
